name: Continuous Deployment
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deployment To Hugging Face
        env:
          HF: ${{ secrets.HF }}
        run: |
            git pull origin update
            git switch update
            pip install -U "huggingface_hub[cli]"
            huggingface-cli login --token "${HF}" --add-to-git-credential
            huggingface-cli upload borjinipun/Drug_Classify ./App --repo-type=space --commit-message="Sync App files"
            huggingface-cli upload borjinipun/Drug_Classify ./Model /Model --repo-type=space --commit-message="Sync Model"
            huggingface-cli upload borjinipun/Drug_Classify ./Results /Metrics --repo-type=space --commit-message="Sync Model"
