name: Continuous Integration
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2
      - name: Install Packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Format
        run: |
          black *.py
      - name: Train
        run: |
          python train.py
      - name: Evaluation
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Model Metrics" > report.md
          cat ./Results/metrics.txt >> report.md
          echo '\n## Confusion Matrix Plot' >> report.md
          echo '![Confusion Matrix](./Results/model_results.png)' >> report.md
          cml comment create report.md

      - name: Update Branch
        run: |
          git commit -m "Update report.md"
          git push --force origin HEAD:update